from django.urls import path
from . import views

urlpatterns = [

    ##NBA##
    path('nbateams/', views.nba_teams, name='nbateams'),

    path('lakers/', views.la_roster, name='lakers'),
    path('clippers/', views.lac_roster, name='clippers'),
    path('warriors/', views.goldenstate_roster, name='warriors'),
    path('knicks/', views.ny_roster, name='knicks'),
    path('thunder/', views.okc_roster, name='thunder'),
    path('spurs/', views.san_roster, name='spurs'),
    path('jazz/', views.utah_roster, name='jazz'),
    path('heat/', views.miami_roster, name='heat'),
    path('celtics/', views.boston_roster, name='celtics'),
    path('mavericks/', views.dallas_roster, name='mavericks'),
    path('nuggets/', views.denver_roster, name='nuggets'),
    path('sixers/', views.philly_roster, name='sixers'),
    path('hawks/', views.atlanta_roster, name='hawks'),
    path('bulls/', views.chicago_roster, name='bulls'),
    path('pistons/', views.detroit_roster, name='pistons'),
    path('rockets/', views.houston_roster, name='rockets'),
    path('pacers/', views.indiana_roster, name='pacers'),
    path('grizzlies/',views.memphis_roster, name='grizzlies'),
    path('magic/', views.orlando_roster, name='magic'),
    path('suns/', views.phoenix_roster, name='suns'),
    path('raptors/', views.toronto_roster, name='raptors'),
    path('nets/', views.brooklyn_roster, name='nets'),
    path('blazers/', views.portland_roster, name='blazers'),
    path('hornets/', views.charlotte_roster, name='hornets'),
    path('cavaliers/', views.cleveland_roster, name='cavaliers'),
    path('bucks/', views.milwaukee_roster, name='bucks'),
    path('timberwolves/',views. minnesota_roster, name='timberwolves'),
    path('pelicans/', views.neworleans_roster, name='pelicans'),
    path('kings/', views.sacramento_roster, name='kings'),
    path('wizards/', views.washington_roster, name='wizards'),

    ##MLB##

    path('mlbteams/', views.mlb_teams, name='mlbteams'),

    path('yankees/', views.yankees_roster, name='Yankees'),
    path('redsox/', views.red_sox_roster, name='Red Sox'),
    path('orioles/', views.orioles_roster, name='Orioles'),
    path('rays/', views.rays_roster, name='Rays'),
    path('bluejays/', views.blue_jays_roster, name='Blue Jays'),
    path('whitesox/', views.white_sox_roster, name='White Sox'),
    path('tigers/', views.tigers_roster, name='Tigers'),
    path('royals/', views.royals_roster, name='Royals'),
    path('twins/', views.twins_roster, name='Twins'),
    path('astros/', views.astros_roster, name='Astros'),
    path('angels/', views.angels_roster, name='Angels'),
    path('athletics/', views.athletics_roster, name='Athletics'),
    path('mariners/', views.mariners_roster, name='Mariners'),
    path('rangers/', views.rangers_roster, name='Rangers'),
    path('braves/', views.braves_roster, name='Braves'),
    path('marlins/', views.marlins_roster, name='Marlins'),
    path('mets/', views.mets_roster, name='Mets'),
    path('phillies/', views.phillies_roster, name='Phillies'),
    path('nationals/', views.nationals_roster, name='Nationals'),
    path('cubs/', views.cubs_roster, name='Cubs'),
    path('reds/', views.reds_roster, name='Reds'),
    path('brewers/', views.brewers_roster, name='Brewers'),
    path('pirates/', views.pirates_roster, name='Pirates'),
    path('cardinals/', views.cardinals_roster, name='Cardinals'),
    path('diamondbacks/',views.dbacks_roster, name='Diamondbacks'),
    path('rockies/', views.rockies_roster, name='Rockies'),
    path('dodgers/', views.dodgers_roster, name='Dodgers'),
    path('padres/', views.padres_roster, name='Padres'),
    path('giants/', views.giants_roster, name='Giants'),
    path('guardians/', views.guardians_roster, name='Guardians'),


    ##NFL
    path('nflteams/', views.nfl_teams, name='nflteams'),


    path("jets/", views.nfl_roster, {"team_abv": "NYJ"}, name="Jets"),
    path("patriots/", views.nfl_roster, {"team_abv": "NE"}, name="Patriots"),
    path("bills/", views.nfl_roster, {"team_abv": "BUF"}, name="Bills"),
    path("dolphins/", views.nfl_roster, {"team_abv": "MIA"}, name="Dolphins"),
    path("ravens/", views.nfl_roster, {"team_abv": "BAL"}, name="Ravens"),
    path("bengals/", views.nfl_roster, {"team_abv": "CIN"}, name="Bengals"),
    path("browns/", views.nfl_roster, {"team_abv": "CLE"}, name="Browns"),
    path("steelers/", views.nfl_roster, {"team_abv": "PIT"}, name="Steelers"),
    path("texans/", views.nfl_roster, {"team_abv": "HOU"}, name="Texans"),
    path("colts/", views.nfl_roster, {"team_abv": "IND"}, name="Colts"),
    path("jaguars/", views.nfl_roster, {"team_abv": "JAX"}, name="Jaguars"),
    path("titans/", views.nfl_roster, {"team_abv": "TEN"}, name="Titans"),
    path("broncos/", views.nfl_roster, {"team_abv": "DEN"}, name="Broncos"),
    path("chiefs/", views.nfl_roster, {"team_abv": "KC"}, name="Chiefs"),
    path("raiders/", views.nfl_roster, {"team_abv": "LV"}, name="Raiders"),
    path("chargers/", views.nfl_roster, {"team_abv": "LAC"}, name="Chargers"),
    path("cowboys/", views.nfl_roster, {"team_abv": "DAL"}, name="Cowboys"),
    path("giants/", views.nfl_roster, {"team_abv": "NYG"}, name="Giants"),
    path("eagles/", views.nfl_roster, {"team_abv": "PHI"}, name="Eagles"),
    path("commanders/", views.nfl_roster, {"team_abv": "WSH"}, name="Commanders"),
    path("bears/", views.nfl_roster, {"team_abv": "CHI"}, name="Bears"),
    path("lions/", views.nfl_roster, {"team_abv": "DET"}, name="Lions"),
    path("packers/", views.nfl_roster, {"team_abv": "GB"}, name="Packers"),
    path("vikings/", views.nfl_roster, {"team_abv": "MIN"}, name="Vikings"),
    path("falcons/", views.nfl_roster, {"team_abv": "ATL"}, name="Falcons"),
    path("panthers/", views.nfl_roster, {"team_abv": "CAR"}, name="Panthers"),
    path("saints/", views.nfl_roster, {"team_abv": "NO"}, name="Saints"),
    path("buccaneers/", views.nfl_roster, {"team_abv": "TB"}, name="Buccaneers"),
    path("cardinals/", views.nfl_roster, {"team_abv": "ARI"}, name="Cardinals"),
    path("rams/", views.nfl_roster, {"team_abv": "LAR"}, name="Rams"),
    path("49ers/", views.nfl_roster, {"team_abv": "SF"}, name="49ers"),
    path("seahawks/", views.nfl_roster, {"team_abv": "SEA"}, name="Seahawks"),


    #####NHL######
    path('nhlteams/', views.nhl_teams, name='nhlteams'),

    path("ducks/", views.nhl_roster, {"id": "24"}, name="Ducks"),
    path("coyotes/", views.nhl_roster, {"id": "53"}, name="Coyotes"),
    path("bruins/", views.nhl_roster, {"id": "6"}, name="Bruins"),
    path("sabres/", views.nhl_roster, {"id": "7"}, name="Sabres"),
    path("flames/", views.nhl_roster, {"id": "20"}, name="Flames"),
    path("hurricanes/", views.nhl_roster, {"id": "12"}, name="Hurricanes"),
    path("blackhawks/", views.nhl_roster, {"id": "16"}, name="Blackhawks"),
    path("avalanche/", views.nhl_roster, {"id": "21"}, name="Avalanche"),
    path("bluejackets/", views.nhl_roster, {"id": "29"}, name="Blue Jackets"),
    path("stars/", views.nhl_roster, {"id": "25"}, name="Stars"),
    path("redwings/", views.nhl_roster, {"id": "17"}, name="Red Wings"),
    path("oilers/", views.nhl_roster, {"id": "22"}, name="Oilers"),
    path("panthers/", views.nhl_roster, {"id": "13"}, name="Panthers"),
    path("kings/", views.nhl_roster, {"id": "26"}, name="Kings"),
    path("wild/", views.nhl_roster, {"id": "30"}, name="Wild"),
    path("canadiens/", views.nhl_roster, {"id": "8"}, name="Canadiens"),
    path("predators/", views.nhl_roster, {"id": "18"}, name="Predators"),
    path("devils/", views.nhl_roster, {"id": "1"}, name="Devils"),
    path("islanders/", views.nhl_roster, {"id": "2"}, name="Islanders"),
    path("rangers/", views.nhl_roster, {"id": "3"}, name="Rangers"),
    path("senators/", views.nhl_roster, {"id": "9"}, name="Senators"),
    path("flyers/", views.nhl_roster, {"id": "4"}, name="Flyers"),
    path("penguins/", views.nhl_roster, {"id": "5"}, name="Penguins"),
    path("sharks/", views.nhl_roster, {"id": "28"}, name="Sharks"),
    path("blues/", views.nhl_roster, {"id": "19"}, name="Blues"),
    path("lightning/", views.nhl_roster, {"id": "14"}, name="Lightning"),
    path("leafs/", views.nhl_roster, {"id": "10"}, name="Maple Leafs"),
    path("canucks/", views.nhl_roster, {"id": "23"}, name="Canucks"),
    path("goldenknights/", views.nhl_roster, {"id": "54"}, name="Golden Knights"),
    path("capitals/", views.nhl_roster, {"id": "15"}, name="Capitals"),
    path("jets/", views.nhl_roster, {"id": "52"}, name="Jets"),
    path("kraken/", views.nhl_roster, {"id": "55"}, name="Kraken"),



    
]