from django.urls import path
from . import views

urlpatterns = [
    path('nbateams/', views.nba_teams, name='nbateams'),
    path('lakers/', views.la_roster, name='lakers'),
    path('clippers/', views.lac_roster, name='clippers'),
    path('warriors/', views.goldenstate_roster, name='warriors'),
    path('knicks/', views.ny_roster, name='knicks'),
    path('thunder/', views.okc_roster, name='thunder'),
    path('spurs/', views.san_roster, name='spurs'),
    path('jazz/', views.utah_roster, name='jazz'),
    path('heat/', views.miami_roster, name='heat'),
    path('celtics/', views.boston_roster, name='celtics'),
    path('mavericks/', views.dallas_roster, name='mavericks'),
    path('nuggets/', views.denver_roster, name='nuggets'),
    path('sixers/', views.philly_roster, name='sixers'),
    path('hawks/', views.atlanta_roster, name='hawks'),
    path('bulls/', views.chicago_roster, name='bulls'),
    path('pistons/', views.detroit_roster, name='pistons'),
    path('rockets/', views.houston_roster, name='rockets'),
    path('pacers/', views.indiana_roster, name='pacers'),
    path('grizzlies/',views.memphis_roster, name='grizzlies'),
    path('magic/', views.orlando_roster, name='magic'),
    path('suns/', views.phoenix_roster, name='suns'),
    path('raptors/', views.toronto_roster, name='raptors'),
    path('nets/', views.brooklyn_roster, name='nets'),
    path('blazers/', views.portland_roster, name='blazers'),
    path('hornets/', views.charlotte_roster, name='hornets'),
    path('cavaliers/', views.cleveland_roster, name='cavaliers'),
    path('bucks/', views.milwaukee_roster, name='bucks'),
    path('timberwolves/',views. minnesota_roster, name='timberwolves'),
    path('pelicans/', views.neworleans_roster, name='pelicans'),
    path('kings/', views.sacramento_roster, name='kings'),
    path('wizards/', views.washington_roster, name='wizards'),
    
]